const Fitness = [
    {
      id: 401,
      category1: "fitness",
      category: "fitness",
      authorName: 'neji hyuga',
      date: "19. aug 2022",
      title: "New Study Finds Lowest Risk of Death Was Among Adults Who Exercised 150-600 Minutes/week",
      cover: "https://c4.wallpaperflare.com/wallpaper/73/900/929/sports-fitness-asian-brunette-wallpaper-preview.jpg",
    },
    {
      id: 402,
      category1: "fitness",
      category: "fitness",
      authorName: 'naruto uzumaki',
      date: "01. sept 2022",
      title: "'No Pain, No Gain' Approach Improves Walking Ability With Peripheral Artery Disease",
      cover: "https://c4.wallpaperflare.com/wallpaper/916/717/109/blonde-pose-workout-fitness-wallpaper-preview.jpg",
    },
    {
      id: 403,
      category1: "fitness",
      category: "fitness",
      authorName: 'sasuke uchia',
      date: "30. aug 2022",
      title: "How Often You Exercise or How Much?",
      cover: "https://c4.wallpaperflare.com/wallpaper/199/924/33/muscle-muscle-bodybuilding-press-wallpaper-preview.jpg",
    },
  
    {
      id: 404,
      category1: "fitness",
      category: "fitness",
      authorName: 'madara uchia',
      date: "11. aug 2022",
      title: "Insufficient Sleep in Teenagers Is Associated With Overweight and Obesity",
      cover: "https://c4.wallpaperflare.com/wallpaper/102/304/5/yoga-5k-jacqueline-fernandez-wallpaper-preview.jpg",
    },
    {
      id: 405,
      category1: "fitness",
      category: "fitness",
      authorName: 'might guy',
      date: "02. aug 2022",
      title: "Physical Activity and Reduced Heart Failure Risk",
      cover: "https://c4.wallpaperflare.com/wallpaper/737/916/1022/sports-other-wallpaper-preview.jpg",
    },
    {
      id: 406,
      category1: "fitness",
      category: "fitness",
      authorName: 'kakashi hatake',
      date: "25. aug 2022",
      title: "75% of Teens Aren't Getting Recommended Daily Exercise",
      cover: "https://c4.wallpaperflare.com/wallpaper/607/163/748/fitness-model-yoga-pants-yoga-gymnastics-wallpaper-preview.jpg",
    },
    {
      id: 407,
      category1: "fitness",
      title: "Physical Activity and Reduced Heart Failure Risk",
      date: "10. March 2022",
      cover: "https://c4.wallpaperflare.com/wallpaper/727/4/1016/men-fitness-model-wallpaper-preview.jpg",
      desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
    },
    {
      id: 408,
      category1: "fitness",
      title: "Leisure Activities That May Lower Risk of Death",
      date: "30. Aug 2022",
      cover: "https://c4.wallpaperflare.com/wallpaper/663/151/617/men-fitness-dumbbells-bodybuilder-wallpaper-preview.jpg",
      desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
    },
    {
      id: 409,
      category1: "fitness",
      title: "How Often You Exercise or How Much?",
      date: "11. Aug 2022",
      cover: "https://c4.wallpaperflare.com/wallpaper/941/520/888/muscle-muscle-press-pose-dumbbells-hd-wallpaper-preview.jpg",
      desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
    },
    {
      id: 410,
      category1: "fitness",
      title: "Brain Benefiting from Moderate Physical Activity",
      date: "23. July 2022",
      cover: "https://c4.wallpaperflare.com/wallpaper/84/855/701/woman-pose-fitness-dumbbells-wallpaper-preview.jpg",
      desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
    },
    {
      id: 411,
      category1: "fitness",
      title: "Children's Health Will Be Negatively Impacted by Poorer Fitness as Global Temperatures Rise, New Research Shows",
      date: "29. Aug 2022",
      cover: "https://c4.wallpaperflare.com/wallpaper/273/215/738/pose-tattoo-muscle-muscle-pose-hd-wallpaper-preview.jpg",
      desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
    },
    {
      id: 412,
      category1: "fitness",
      title: "Most High Blood Pressure in Children and Teenagers Is Linked With Unhealthy Lifestyle",
      date: "19. feb 2022",
      cover: "https://c4.wallpaperflare.com/wallpaper/973/896/874/fitness-gym-dumbbells-sportswear-wallpaper-preview.jpg",
      desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
    },
    {
      id: 413,
      category1: "fitness",
      title: "US Promises to give Intel aid to locate the soldiers",
      cover: "https://c4.wallpaperflare.com/wallpaper/48/549/285/workout-fitness-crossfit-training-ball-wallpaper-preview.jpg",
    },
    {
      id: 414,
      category1: "fitness",
      title: "Renewable energy dead as industry waits for Policy",
      cover: "https://c4.wallpaperflare.com/wallpaper/322/962/354/muscle-rod-pose-training-athlete-hd-wallpaper-preview.jpg",
    },
    {
      id: 415,
      category1: "fitness",
      title: "Mount Etna erupts fashion in nice looking pictures",
      cover: "https://c0.wallpaperflare.com/preview/787/856/40/dumbell-barbell-bodybuilding-equipment.jpg",
    },
    {
      id: 416,
      category1: "fitness",
      title: "US Promises to give Intel aid to locate the soldiers",
      cover: "https://c1.wallpaperflare.com/preview/379/871/628/people-exercise-fit-fitness.jpg",
    },
    {
      id: 417,
      category1: "fitness",
      title: "Renewable energy dead as industry waits for Policy",
      cover: "https://c1.wallpaperflare.com/preview/981/336/896/people-diet-fit-fitness.jpg",
    },
    {
      id: 418,
      category1: "fitness",
      title: "Mount Etna erupts fashion in nice looking pictures",
      cover: "https://c1.wallpaperflare.com/preview/660/690/486/weights-health-happy-sports-thumbnail.jpg",
    },
    {
      id: 419,
      category1: "fitnessSideCard",
      title: "US Promises to give Intel aid to locate the soldiers",
      cover: "https://c1.wallpaperflare.com/preview/379/871/628/people-exercise-fit-fitness.jpg",
    },
    {
      id: 420,
      category1: "fitnessSideCard",
      title: "Renewable energy dead as industry waits for Policy",
      cover: "https://c1.wallpaperflare.com/preview/379/871/628/people-exercise-fit-fitness.jpg",
    },
    {
      id: 421,
      category1: "fitnessSideCard",
      title: "Mount Etna erupts fashion in nice looking pictures",
      cover: "https://c0.wallpaperflare.com/preview/787/856/40/dumbell-barbell-bodybuilding-equipment.jpg",
    },
    {
      id: 422,
      category1: "fitnessSideCard",
      title: "US Promises to give Intel aid to locate the soldiers",
      cover: "https://c4.wallpaperflare.com/wallpaper/322/962/354/muscle-rod-pose-training-athlete-hd-wallpaper-preview.jpg",
    },
    {
      id: 423,
      category1: "fitnessSideCard",
      title: "Renewable energy dead as industry waits for Policy",
      cover: "https://c4.wallpaperflare.com/wallpaper/48/549/285/workout-fitness-crossfit-training-ball-wallpaper-preview.jpg",
    },
    {
      id: 424,
      category1: "fitnessSideCard",
      title: "Mount Etna erupts fashion in nice looking pictures",
      cover: "https://c1.wallpaperflare.com/preview/660/690/486/weights-health-happy-sports-thumbnail.jpg",
    },
  
  ]

  module.exports = Fitness;