const Home1Data = [
  {
    id: 1,
    cover: "https://c0.wallpaperflare.com/preview/330/490/484/business-office-computer-flatlay.jpg",
    category: "featured",
    title: "Google To Boost Android Security In Few Days",
    authorName: "rutvik jathar",
    authorImg: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    date: "26 Aug - 2022",
    desc: [
      {
        para1: "You audience. Least, the recently his repeat the this avarice for the have and was on would before the concise bedding were hall politely name be regretting have of even five of it the his are there again. Word seven designer far lady problem will have work with you to fully understand your business to achieve.",
      },
      {
        para2: "We work with clients big and small across a range of sectors and we utilize all forms of media to get your name out there in a way that’s right for you. We believe that analysis of your company and your customers is key in responding effectively to your promotional needs and we will work with you.",
      },
      {
        para3: "We have a number of different teams within our agency that specialise in different areas of business so you can be sure that you won’t receive a generic service and although we can’t boast years and years of service we can ensure you that is a good thing in this industry.",
      },
    ],
    details: [
      {
        title: "Starting a new company is easy",
      },
      { para1: "Our teams are up to date with the latest technologies, media trends and are keen to prove themselves in this industry and that’s what you want from an advertising agency, not someone who is relying on the same way of doing things that worked 10 years, 5 years or even a year ago." },
      {
        quote: "Scarfs, still not this no with explains it me and option on the any options roasted when I and state can that an don't subjective of has his take on and in from royal everything took raising our have behind success you the mechanic.",
      },
      {
        para2: "And, higher by agency; In from their in and we spirit, through merely and doctor's small him sounded a all now, with that put gift white highly geared that was left back as of or logged important. A over have the large try understanding the believe. Perfected been viewer. Shreds early willingly safely what passion the.",
      },
      {
        para3: "In an ideal world this website wouldn’t exist, a client would acknowledge the importance of having web copy before the design starts. Needless to say it’s very important, content is king and people are beginning to understand that. However, back over in reality some project schedules and budgets don’t allow for web copy to be written before the design phase, this is sad but true.",
      },
    ],
  },
  {
    id: 2,
    cover: "https://c4.wallpaperflare.com/wallpaper/333/163/623/sport-football-nike-lionel-messi-wallpaper-preview.jpg",
    category: "sport",
    title: "More than billion football fans attend Brazil world cup",
    authorName: "nitin kanhurkar",
    authorImg: "https://wtax-am.sagacom.com/files/2020/07/man-modern-7-22-20-shutterstock_1654428361-620x400.jpg",
    date: "25 Aug - 2022",
    desc: [
      {
        para1: "You audience. Least, the recently his repeat the this avarice for the have and was on would before the concise bedding were hall politely name be regretting have of even five of it the his are there again. Word seven designer far lady problem will have work with you to fully understand your business to achieve.",
      },
      {
        para2: "We work with clients big and small across a range of sectors and we utilize all forms of media to get your name out there in a way that’s right for you. We believe that analysis of your company and your customers is key in responding effectively to your promotional needs and we will work with you.",
      },
      {
        para3: "We have a number of different teams within our agency that specialise in different areas of business so you can be sure that you won’t receive a generic service and although we can’t boast years and years of service we can ensure you that is a good thing in this industry.",
      },
    ],
    details: [
      {
        title: "Starting a new company is easy",
      },
      { para1: "Our teams are up to date with the latest technologies, media trends and are keen to prove themselves in this industry and that’s what you want from an advertising agency, not someone who is relying on the same way of doing things that worked 10 years, 5 years or even a year ago." },
      {
        quote: "Scarfs, still not this no with explains it me and option on the any options roasted when I and state can that an don't subjective of has his take on and in from royal everything took raising our have behind success you the mechanic.",
      },
      {
        para2: "And, higher by agency; In from their in and we spirit, through merely and doctor's small him sounded a all now, with that put gift white highly geared that was left back as of or logged important. A over have the large try understanding the believe. Perfected been viewer. Shreds early willingly safely what passion the.",
      },
      {
        para3: "In an ideal world this website wouldn’t exist, a client would acknowledge the importance of having web copy before the design starts. Needless to say it’s very important, content is king and people are beginning to understand that. However, back over in reality some project schedules and budgets don’t allow for web copy to be written before the design phase, this is sad but true.",
      },
    ],
  },
  {
    id: 3,
    cover: "https://c4.wallpaperflare.com/wallpaper/718/629/245/5bd3858d002d2-wallpaper-preview.jpg",
    category: "Technology",
    title: "No escaping new high tech speed cameras",
    authorName: "kalyani shinde",
    authorImg: "https://mcdn.wallpapersafari.com/medium/85/40/pPM94O.jpg",
    date: "24 Aug - 2022",
    desc: [
      {
        para1: "You audience. Least, the recently his repeat the this avarice for the have and was on would before the concise bedding were hall politely name be regretting have of even five of it the his are there again. Word seven designer far lady problem will have work with you to fully understand your business to achieve.",
      },
      {
        para2: "We work with clients big and small across a range of sectors and we utilize all forms of media to get your name out there in a way that’s right for you. We believe that analysis of your company and your customers is key in responding effectively to your promotional needs and we will work with you.",
      },
      {
        para3: "We have a number of different teams within our agency that specialise in different areas of business so you can be sure that you won’t receive a generic service and although we can’t boast years and years of service we can ensure you that is a good thing in this industry.",
      },
    ],
    details: [
      {
        title: "Starting a new company is easy",
      },
      { para1: "Our teams are up to date with the latest technologies, media trends and are keen to prove themselves in this industry and that’s what you want from an advertising agency, not someone who is relying on the same way of doing things that worked 10 years, 5 years or even a year ago." },
      {
        quote: "Scarfs, still not this no with explains it me and option on the any options roasted when I and state can that an don't subjective of has his take on and in from royal everything took raising our have behind success you the mechanic.",
      },
      {
        para2: "And, higher by agency; In from their in and we spirit, through merely and doctor's small him sounded a all now, with that put gift white highly geared that was left back as of or logged important. A over have the large try understanding the believe. Perfected been viewer. Shreds early willingly safely what passion the.",
      },
      {
        para3: "In an ideal world this website wouldn’t exist, a client would acknowledge the importance of having web copy before the design starts. Needless to say it’s very important, content is king and people are beginning to understand that. However, back over in reality some project schedules and budgets don’t allow for web copy to be written before the design phase, this is sad but true.",
      },
    ],
  },
  {
    id: 4,
    cover: "https://c4.wallpaperflare.com/wallpaper/498/478/483/emma-watson-women-actress-armpits-wallpaper-preview.jpg",
    category: "HollyWood",
    title: "Emma Watson stands up for Turkish women",
    authorName: "ankush aghawane",
    authorImg: "http://images.huffingtonpost.com/2016-12-10-1481348838-4670175-IMG_31751.JPG",
    date: "25 Aug - 2022",
    desc: [
      {
        para1: "You audience. Least, the recently his repeat the this avarice for the have and was on would before the concise bedding were hall politely name be regretting have of even five of it the his are there again. Word seven designer far lady problem will have work with you to fully understand your business to achieve.",
      },
      {
        para2: "We work with clients big and small across a range of sectors and we utilize all forms of media to get your name out there in a way that’s right for you. We believe that analysis of your company and your customers is key in responding effectively to your promotional needs and we will work with you.",
      },
      {
        para3: "We have a number of different teams within our agency that specialise in different areas of business so you can be sure that you won’t receive a generic service and although we can’t boast years and years of service we can ensure you that is a good thing in this industry.",
      },
    ],
    details: [
      {
        title: "Starting a new company is easy",
      },
      { para1: "Our teams are up to date with the latest technologies, media trends and are keen to prove themselves in this industry and that’s what you want from an advertising agency, not someone who is relying on the same way of doing things that worked 10 years, 5 years or even a year ago." },
      {
        quote: "Scarfs, still not this no with explains it me and option on the any options roasted when I and state can that an don't subjective of has his take on and in from royal everything took raising our have behind success you the mechanic.",
      },
      {
        para2: "And, higher by agency; In from their in and we spirit, through merely and doctor's small him sounded a all now, with that put gift white highly geared that was left back as of or logged important. A over have the large try understanding the believe. Perfected been viewer. Shreds early willingly safely what passion the.",
      },
      {
        para3: "In an ideal world this website wouldn’t exist, a client would acknowledge the importance of having web copy before the design starts. Needless to say it’s very important, content is king and people are beginning to understand that. However, back over in reality some project schedules and budgets don’t allow for web copy to be written before the design phase, this is sad but true.",
      },
    ],
  },
]
//51-100
const LatestArticleData = [
  {
    id: 51,
    category: "fun",
    title: "Our Favorite Photos From All Around",
    authorName: 'naruto uzumaki',
    date: "01. sept 2022",
    cover: "https://c1.wallpaperflare.com/preview/969/671/768/adventure-back-care-casual.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
  },
  {
    id: 52,
    category: "fun",
    title: "Places To Visit For A Peaceful Holiday",
    authorName: 'sasuke uchia',
    date: "30. aug 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/265/733/93/architecture-city-travel-europe-wallpaper-preview.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
  },
  {
    id: 53,
    category: "fun",
    title: "Is This The New Boxing Champion?",
    authorName: 'kakashi hatake',
    date: "25. aug 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/462/606/385/muhammad-ali-monochrome-sport-boxing-wallpaper-preview.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
  },
  {
    id: 54,
    category: "fun",
    title: "A Detailed Retelling Of Our Trek Through The Dangerous Alps",
    authorName: 'neji hyuga',
    date: "19. aug 2022",
    cover: "https://c1.wallpaperflare.com/preview/503/726/498/travel-travel-adventure-adventure-mountain.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
  },
  {
    id: 55,
    category: "fun",
    title: "Natural Sunlight Boosts Your Immunity",
    authorName: 'madara uchia',
    date: "11. aug 2022",
    cover: "https://c1.wallpaperflare.com/preview/674/789/252/afternoon-dancing-female-photos.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
  },
  {
    id: 56,
    category: "fun",
    title: "Health Benefits From Asparagus",
    authorName: 'might guy',
    date: "02. aug 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/339/125/238/wine-food-meat-bbq-wallpaper-preview.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
  },
  {
    id: 57,
    category: "fun1",
    title: "Lorem ipsum dolor sit amet",
    date: "19. February 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/365/244/884/uchiha-itachi-naruto-shippuuden-anbu-silhouette-wallpaper-preview.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
  },
  {
    id: 58,
    category: "fun1",
    title: "Lorem ipsum dolor sit amet",
    date: "19. February 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/365/244/884/uchiha-itachi-naruto-shippuuden-anbu-silhouette-wallpaper-preview.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
  },
  {
    id: 59,
    category: "fun1",
    title: "Lorem ipsum dolor sit amet",
    date: "19. February 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/365/244/884/uchiha-itachi-naruto-shippuuden-anbu-silhouette-wallpaper-preview.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
  },
  {
    id: 60,
    category: "fitness",
    title: "'No Pain, No Gain' Approach Improves Walking Ability With Peripheral Artery Disease",
    date: "19. February 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/916/717/109/blonde-pose-workout-fitness-wallpaper-preview.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
  },
  {
    id: 61,
    category: "fitness",
    title: "Researchers Discover Gene That Promotes Muscle Strength During Exercise",
    date: "19. February 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/199/924/33/muscle-muscle-bodybuilding-press-wallpaper-preview.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
  },
]
//101-150
const tpost = [
  {
    id: 101,
    authorName: 'naruto uzumaki',
    date: "01. sept 2022",
    title: "US Promises to give Intel aid to locate the soldiers",
    cover: "https://c4.wallpaperflare.com/wallpaper/920/293/266/tower-block-new-york-usa-united-states-wallpaper-preview.jpg",
  },
  {
    id: 102,
    authorName: 'sasuke uchia',
    date: "30. aug 2022",
    title: "Renewable energy dead as industry waits for Policy",
    cover: "https://c4.wallpaperflare.com/wallpaper/646/835/697/full-size-for-desktop-nature-pictures-1920x1080-wallpaper-preview.jpg",
  },
  {
    id: 103,
    authorName: 'kakashi hatake',
    date: "25. aug 2022",
    title: "Mount Etna erupts fashion in nice looking pictures",
    cover: "https://c4.wallpaperflare.com/wallpaper/428/12/969/volcano-smoke-sky-snow-wallpaper-preview.jpg",
  },
  {
    id: 104,
    authorName: 'neji hyuga',
    date: "19. aug 2022",
    title: "Travelers spotted a bald eagle at the airport — but this isn't his first TSA line",
    cover: "https://c4.wallpaperflare.com/wallpaper/751/418/477/landscape-photography-of-green-grass-hills-during-daytime-rocky-mountain-national-park-rocky-mountain-national-park-wallpaper-preview.jpg",
  },
  {
    id: 105,
    authorName: 'madara uchia',
    date: "11. aug 2022",
    title: "Sharks mistaking feet for fish are likely behind Long Island attacks",
    cover: "https://c4.wallpaperflare.com/wallpaper/934/523/722/animals-shark-underwater-great-white-shark-wallpaper-preview.jpg",
  },
  {
    id: 106,
    authorName: 'might guy',
    date: "02. aug 2022",
    title: "What a pest! Spotted lanternflies are spreading in the U.S.",
    cover: "https://media.npr.org/assets/img/2022/08/17/ap21254030413843_wide-273914e5d32d03097106cda756190b7d93b01099-s700-c85.webp",
  },
  {
    id: 107,
    authorName: 'naruto uzumaki',
    date: "01. sept 2022",
    title: "US Promises to give Intel aid to locate the soldiers",
    cover: "https://c4.wallpaperflare.com/wallpaper/920/293/266/tower-block-new-york-usa-united-states-wallpaper-preview.jpg",
  },
  {
    id: 108,
    authorName: 'sasuke uchia',
    date: "30. aug 2022",
    title: "Renewable energy dead as industry waits for Policy",
    cover: "https://c4.wallpaperflare.com/wallpaper/646/835/697/full-size-for-desktop-nature-pictures-1920x1080-wallpaper-preview.jpg",
  },
  {
    id: 109,
    authorName: 'kakashi hatake',
    date: "25. aug 2022",
    title: "Mount Etna erupts fashion in nice looking pictures",
    cover: "https://c4.wallpaperflare.com/wallpaper/428/12/969/volcano-smoke-sky-snow-wallpaper-preview.jpg",
  },
  {
    id: 110,
    authorName: 'neji hyuga',
    date: "19. aug 2022",
    title: "Travelers spotted a bald eagle at the airport — but this isn't his first TSA line",
    cover: "https://c4.wallpaperflare.com/wallpaper/751/418/477/landscape-photography-of-green-grass-hills-during-daytime-rocky-mountain-national-park-rocky-mountain-national-park-wallpaper-preview.jpg",
  },
  {
    id: 111,
    authorName: 'madara uchia',
    date: "11. aug 2022",
    title: "Sharks mistaking feet for fish are likely behind Long Island attacks",
    cover: "https://c4.wallpaperflare.com/wallpaper/934/523/722/animals-shark-underwater-great-white-shark-wallpaper-preview.jpg",
  },
  {
    id: 112,
    authorName: 'might guy',
    date: "02. aug 2022",
    title: "What a pest! Spotted lanternflies are spreading in the U.S.",
    cover: "https://media.npr.org/assets/img/2022/08/17/ap21254030413843_wide-273914e5d32d03097106cda756190b7d93b01099-s700-c85.webp",
  },
]
//151-200
const lifestyle = [
  {
    id: 151,
    category: "world",
    category1: "card1",
    title: "Mustang Teases With A New Promo",
    authorName: 'naruto uzumaki',
    date: "01. sept 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/910/24/10/night-artwork-futuristic-city-cyberpunk-wallpaper-preview.jpg",
  },
  {
    id: 152,
    category: "sport",
    category1: "card1",
    title: "With A Whirr, Not A Roar, Auto Racing Drives Toward An Electric Future",
    authorName: 'sasuke uchia',
    date: "30. aug 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/943/63/773/cyberpunk-2077-cyberpunk-video-games-wallpaper-preview.jpg",
  },
  {
    id: 153,
    category: "fashion",
    category1: "card1",
    title: "Learn How To Nail Your Favorite Look All Time",
    authorName: 'kakashi hatake',
    date: "25. aug 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/1020/921/305/artwork-digital-art-cat-glasses-wallpaper-preview.jpg",
  },
  {
    id: 154,
    category: "culture",
    category1: "card2",
    title: "Indians Are Partying And Praying For Elephant-Headed God Ganesh",
    authorName: 'neji hyuga',
    date: "19. aug 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/462/491/817/lord-ganesha-ganpati-bappa-ganapati-4k-wallpaper-preview.jpg",
  },
  {
    id: 155,
    category: "wild",
    category1: "card2",
    title: "There are 40% more tigers in the world than previously estimated",
    authorName: 'madara uchia',
    date: "11. aug 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/121/838/467/art-artistic-graphic-design-wallpaper-preview.jpg",
  },
  {
    id: 156,
    category: "nature",
    category1: "card2",
    title: "Travel plans to or across Europe? Prepare for long lines",
    authorName: 'might guy',
    date: "02. aug 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/362/276/920/nature-4k-pc-full-hd-wallpaper-preview.jpg",
  },

]
//401-450
const Fitness = [
  {
    id: 401,
    category1: "fitness",
    category: "fitness",
    authorName: 'neji hyuga',
    date: "19. aug 2022",
    title: "New Study Finds Lowest Risk of Death Was Among Adults Who Exercised 150-600 Minutes/week",
    cover: "https://c4.wallpaperflare.com/wallpaper/73/900/929/sports-fitness-asian-brunette-wallpaper-preview.jpg",
  },
  {
    id: 402,
    category1: "fitness",
    category: "fitness",
    authorName: 'naruto uzumaki',
    date: "01. sept 2022",
    title: "'No Pain, No Gain' Approach Improves Walking Ability With Peripheral Artery Disease",
    cover: "https://c4.wallpaperflare.com/wallpaper/916/717/109/blonde-pose-workout-fitness-wallpaper-preview.jpg",
  },
  {
    id: 403,
    category1: "fitness",
    category: "fitness",
    authorName: 'sasuke uchia',
    date: "30. aug 2022",
    title: "How Often You Exercise or How Much?",
    cover: "https://c4.wallpaperflare.com/wallpaper/199/924/33/muscle-muscle-bodybuilding-press-wallpaper-preview.jpg",
  },

  {
    id: 404,
    category1: "fitness",
    category: "fitness",
    authorName: 'madara uchia',
    date: "11. aug 2022",
    title: "Insufficient Sleep in Teenagers Is Associated With Overweight and Obesity",
    cover: "https://c4.wallpaperflare.com/wallpaper/102/304/5/yoga-5k-jacqueline-fernandez-wallpaper-preview.jpg",
  },
  {
    id: 405,
    category1: "fitness",
    category: "fitness",
    authorName: 'might guy',
    date: "02. aug 2022",
    title: "Physical Activity and Reduced Heart Failure Risk",
    cover: "https://c4.wallpaperflare.com/wallpaper/737/916/1022/sports-other-wallpaper-preview.jpg",
  },
  {
    id: 406,
    category1: "fitness",
    category: "fitness",
    authorName: 'kakashi hatake',
    date: "25. aug 2022",
    title: "75% of Teens Aren't Getting Recommended Daily Exercise",
    cover: "https://c4.wallpaperflare.com/wallpaper/607/163/748/fitness-model-yoga-pants-yoga-gymnastics-wallpaper-preview.jpg",
  },
  {
    id: 407,
    category1: "fitness",
    title: "Physical Activity and Reduced Heart Failure Risk",
    date: "10. March 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/727/4/1016/men-fitness-model-wallpaper-preview.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
  },
  {
    id: 408,
    category1: "fitness",
    title: "Leisure Activities That May Lower Risk of Death",
    date: "30. Aug 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/663/151/617/men-fitness-dumbbells-bodybuilder-wallpaper-preview.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
  },
  {
    id: 409,
    category1: "fitness",
    title: "How Often You Exercise or How Much?",
    date: "11. Aug 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/941/520/888/muscle-muscle-press-pose-dumbbells-hd-wallpaper-preview.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
  },
  {
    id: 410,
    category1: "fitness",
    title: "Brain Benefiting from Moderate Physical Activity",
    date: "23. July 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/84/855/701/woman-pose-fitness-dumbbells-wallpaper-preview.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
  },
  {
    id: 411,
    category1: "fitness",
    title: "Children's Health Will Be Negatively Impacted by Poorer Fitness as Global Temperatures Rise, New Research Shows",
    date: "29. Aug 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/273/215/738/pose-tattoo-muscle-muscle-pose-hd-wallpaper-preview.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
  },
  {
    id: 412,
    category1: "fitness",
    title: "Most High Blood Pressure in Children and Teenagers Is Linked With Unhealthy Lifestyle",
    date: "19. feb 2022",
    cover: "https://c4.wallpaperflare.com/wallpaper/973/896/874/fitness-gym-dumbbells-sportswear-wallpaper-preview.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
  },
  {
    id: 413,
    category1: "fitness",
    title: "US Promises to give Intel aid to locate the soldiers",
    cover: "https://c4.wallpaperflare.com/wallpaper/48/549/285/workout-fitness-crossfit-training-ball-wallpaper-preview.jpg",
  },
  {
    id: 414,
    category1: "fitness",
    title: "Renewable energy dead as industry waits for Policy",
    cover: "https://c4.wallpaperflare.com/wallpaper/322/962/354/muscle-rod-pose-training-athlete-hd-wallpaper-preview.jpg",
  },
  {
    id: 415,
    category1: "fitness",
    title: "Mount Etna erupts fashion in nice looking pictures",
    cover: "https://c0.wallpaperflare.com/preview/787/856/40/dumbell-barbell-bodybuilding-equipment.jpg",
  },
  {
    id: 416,
    category1: "fitness",
    title: "US Promises to give Intel aid to locate the soldiers",
    cover: "https://c1.wallpaperflare.com/preview/379/871/628/people-exercise-fit-fitness.jpg",
  },
  {
    id: 417,
    category1: "fitness",
    title: "Renewable energy dead as industry waits for Policy",
    cover: "https://c1.wallpaperflare.com/preview/981/336/896/people-diet-fit-fitness.jpg",
  },
  {
    id: 418,
    category1: "fitness",
    title: "Mount Etna erupts fashion in nice looking pictures",
    cover: "https://c1.wallpaperflare.com/preview/660/690/486/weights-health-happy-sports-thumbnail.jpg",
  },
  {
    id: 419,
    category1: "fitnessSideCard",
    title: "US Promises to give Intel aid to locate the soldiers",
    cover: "https://c1.wallpaperflare.com/preview/379/871/628/people-exercise-fit-fitness.jpg",
  },
  {
    id: 420,
    category1: "fitnessSideCard",
    title: "Renewable energy dead as industry waits for Policy",
    cover: "https://c1.wallpaperflare.com/preview/379/871/628/people-exercise-fit-fitness.jpg",
  },
  {
    id: 421,
    category1: "fitnessSideCard",
    title: "Mount Etna erupts fashion in nice looking pictures",
    cover: "https://c0.wallpaperflare.com/preview/787/856/40/dumbell-barbell-bodybuilding-equipment.jpg",
  },
  {
    id: 422,
    category1: "fitnessSideCard",
    title: "US Promises to give Intel aid to locate the soldiers",
    cover: "https://c4.wallpaperflare.com/wallpaper/322/962/354/muscle-rod-pose-training-athlete-hd-wallpaper-preview.jpg",
  },
  {
    id: 423,
    category1: "fitnessSideCard",
    title: "Renewable energy dead as industry waits for Policy",
    cover: "https://c4.wallpaperflare.com/wallpaper/48/549/285/workout-fitness-crossfit-training-ball-wallpaper-preview.jpg",
  },
  {
    id: 424,
    category1: "fitnessSideCard",
    title: "Mount Etna erupts fashion in nice looking pictures",
    cover: "https://c1.wallpaperflare.com/preview/660/690/486/weights-health-happy-sports-thumbnail.jpg",
  },

]
//451-500
const HealthyFood = [
  {
    id: 451,
    category1: "fitness",
    category: "food",
    authorName: 'naruto uzumaki',
    date: "01. sept 2022",
    title: "The Habit Burger Grill Is Bringing Their Signature Flavor to Butte County With New Drive-Thru Restaurant",
    cover: "https://c4.wallpaperflare.com/wallpaper/374/404/846/brown-bird-perching-during-daytime-wren-wren-wallpaper-preview.jpg",
  },
  {
    id: 452,
    category1: "fitness",
    category: "food",
    authorName: 'sasuke uchia',
    date: "30. aug 2022",
    title: "Vitamin B12 Foods: Low Stamina And Strength? Do Add These Vitamin B12 Rich Food Items In Your Diet",
    cover: "https://c4.wallpaperflare.com/wallpaper/311/699/596/fruit-allsorts-pineapple-melon-wallpaper-preview.jpg",
  },
  {
    id: 453,
    category1: "fitness",
    category: "food",
    authorName: 'kakashi hatake',
    date: "25. aug 2022",
    title: "Weight Loss Tips: Add These Fruit Juices To Your Daily Diet  ",
    cover: "https://c4.wallpaperflare.com/wallpaper/421/594/566/watermelon-kiwi-juice-glasses-wallpaper-preview.jpg",
  },
  {
    id: 454,
    category1: "fitness",
    category: "food",
    authorName: 'neji hyuga',
    date: "19. aug 2022",
    title: "Chennai restaurant shut down after woman finds worms in food",
    cover: "https://c4.wallpaperflare.com/wallpaper/1016/528/45/cuisine-food-india-indian-wallpaper-preview.jpg",
  },
  {
    id: 455,
    category1: "fitness",
    category: "food",
    authorName: 'madara uchia',
    date: "11. aug 2022",
    title: "64 healthy dinner recipes that require little to no effort",
    cover: "https://c4.wallpaperflare.com/wallpaper/3/13/72/rolls-sushi-japanese-food-fruits-wallpaper-preview.jpg",
  },
  {
    id: 456,
    category1: "fitness",
    category: "food",
    authorName: 'might guy',
    date: "02. aug 2022",
    title: "Pizza Hut brings in late-night munchies tax to combat inflation",
    cover: "https://c4.wallpaperflare.com/wallpaper/234/543/684/food-pizza-wallpaper-preview.jpg",
  }
]
//501-550
const Technology1 = [
  {
    id: 501,
    category1: "fitness",
    category: "technology",
    authorName: 'naruto uzumaki',
    date: "01. sept 2022",
    title: "Life without reliable internet remains a daily struggle for millions of Americans",
    cover: "https://c4.wallpaperflare.com/wallpaper/653/228/905/internet-internet-hi-tech-security-wallpaper-preview.jpg",
  },
  {
    id: 502,
    category1: "fitness",
    category: "technology",
    authorName: 'sasuke uchia',
    date: "30. aug 2022",
    title: "When does life begin? As state laws define it, science, politics and religion clash",
    cover: "https://c4.wallpaperflare.com/wallpaper/800/399/818/simple-background-robot-digital-art-artificial-intelligence-technology-hi-tech-wallpaper-preview.jpg",
  },
  {
    id: 503,
    category1: "fitness",
    category: "technology",
    authorName: 'kakashi hatake',
    date: "25. aug 2022",
    title: "FTC sues to block big semiconductor chip industry merger between Nvidia and Arm",
    cover: "https://c0.wallpaperflare.com/preview/841/173/306/web-network-technology-developer.jpg",
  },
  {
    id: 504,
    category1: "fitness",
    category: "technology",
    authorName: 'neji hyuga',
    date: "19. aug 2022",
    title: "NASA is going back to the moon. What's different this time?",
    cover: "https://c4.wallpaperflare.com/wallpaper/618/385/72/fantasy-art-science-fiction-space-suit-artwork-wallpaper-preview.jpg",
  },
  {
    id: 505,
    category1: "fitness",
    category: "technology",
    authorName: 'madara uchia',
    date: "11. aug 2022",
    title: "NASA is set to launch another rocket to the moon",
    cover: "https://c4.wallpaperflare.com/wallpaper/62/181/260/science-fiction-digital-art-render-spaceship-wallpaper-preview.jpg",
  },
  {
    id: 506,
    category1: "fitness",
    category: "technology",
    authorName: 'might guy',
    date: "02. aug 2022",
    title: "Facebook plans to hire 10,000 in Europe to build a virtual reality-based 'metaverse'",
    cover: "https://c4.wallpaperflare.com/wallpaper/864/820/999/gadget-tablet-smartphone-icons-wallpaper-preview.jpg",
  }
]
//551-600
const HollyWood1 = [
  {
    id: 551,
    category1: "fitness",
    category: "hollywood",
    authorName: 'naruto uzumaki',
    date: "01. sept 2022",
    title: "Emilia Clarke On 'Last Christmas,' Brexit And Life After 'Game Of Thrones'",
    cover: "https://c4.wallpaperflare.com/wallpaper/950/652/865/hollywood-actress-emilia-clarke-wallpaper-preview.jpg",
  },
  {
    id: 552,
    category1: "fitness",
    category: "hollywood",
    authorName: 'sasuke uchia',
    date: "30. aug 2022",
    title: "Johnny Depp makes bizarre surprise cameo at 2022 VMAs: 'I needed the work'",
    cover: "https://c4.wallpaperflare.com/wallpaper/937/524/836/johnny-depp-glasses-look-gesture-wallpaper-preview.jpg",
  },
  {
    id: 553,
    category1: "fitness",
    category: "hollywood",
    authorName: 'kakashi hatake',
    date: "25. aug 2022",
    title: "Thor: Love And Thunder’s Mixed Reception Makes Marvel Show Taika Waititi The Way Out Of The Franchise For Thor 5? Heartbreaking News For Fans!",
    cover: "https://c4.wallpaperflare.com/wallpaper/687/639/814/natalie-portman-brunette-thor-marvel-the-dark-world-chris-hemsworth-anthony-hopkins-hd-wallpaper-preview.jpg",
  },
  {
    id: 554,
    category1: "fitness",
    category: "hollywood",
    authorName: 'neji hyuga',
    date: "19. aug 2022",
    title: "Joker Sequel Remains the Only DC Film With an Official Green Light at Warner Bros.",
    cover: "https://c4.wallpaperflare.com/wallpaper/822/647/579/batman-the-dark-knight-joker-face-hd-wallpaper-preview.jpg",
  },
  {
    id: 555,
    category1: "fitness",
    category: "hollywood",
    authorName: 'madara uchia',
    date: "11. aug 2022",
    title: "Why Robert Downey Jr Left The MCU & Iron Man",
    cover: "https://c4.wallpaperflare.com/wallpaper/48/228/880/look-iron-man-robert-downey-jr-marvel-wallpaper-preview.jpg",
  },
  {
    id: 556,
    category1: "fitness",
    category: "hollywood",
    authorName: 'might guy',
    date: "02. aug 2022",
    title: "Fast and Furious 10 shoot in Los Angeles faces protest from residents over ‘dangerous car stunts’",
    cover: "https://c4.wallpaperflare.com/wallpaper/886/19/631/furious-7-fast-and-furious-paul-walker-vin-diesel-wallpaper-preview.jpg",
  }
]
//601-650
const BollyWood1 = [
  {
    id: 601,
    category1: "fitness",
    category: "bollywood",
    authorName: 'naruto uzumaki',
    date: "01. sept 2022",
    title: "'Ek Villain Returns: First song of film 'Galliyan Returns'",
    cover: "https://c4.wallpaperflare.com/wallpaper/225/159/817/movies-bollywood-movies-wallpaper-preview.jpg",
  },
  {
    id: 602,
    category1: "fitness",
    category: "bollywood",
    authorName: 'sasuke uchia',
    date: "30. aug 2022",
    title: "Hrithik Roshan starrer Vikram Vedha teaser creates history, crosses one million likes in less than two days",
    cover: "https://c4.wallpaperflare.com/wallpaper/522/572/1020/movies-bollywood-movies-wallpaper-preview.jpg",
  },
  {
    id: 603,
    category1: "fitness",
    category: "bollywood",
    authorName: 'kakashi hatake',
    date: "25. aug 2022",
    title: "Brahmastra 2 To Create History By Bringing Ranveer Singh, Deepika Padukone, Ranbir Kapoor & Alia Bhatt Together In A Film?",
    cover: "https://c4.wallpaperflare.com/wallpaper/525/218/557/deepika-padukone-ranveer-singh-bollywood-movies-wallpaper-preview.jpg",
  },
  {
    id: 604,
    category1: "fitness",
    category: "bollywood",
    authorName: 'neji hyuga',
    date: "19. aug 2022",
    title: "Here’s how Shah Rukh Khan reacted to Fabulous Lives of Bollywood Wives",
    cover: "https://c4.wallpaperflare.com/wallpaper/660/317/106/movies-bollywood-movies-wallpaper-preview.jpg",
  },
  {
    id: 605,
    category1: "fitness",
    category: "bollywood",
    authorName: 'madara uchia',
    date: "11. aug 2022",
    title: "Aamir Khan breaks silence after Laal Singh Chaddha’s disastrous performance, shares ‘Michhami Dukkadam’ post: ‘If I have offended you…’",
    cover: "https://c4.wallpaperflare.com/wallpaper/798/127/832/aamir-khan-bollywood-actor-wallpaper-preview.jpg",
  },
  {
    id: 606,
    category1: "fitness",
    category: "bollywood",
    authorName: 'might guy',
    date: "02. aug 2022",
    title: "Aishwarya Rai's huge update on Ponniyin Selvan!",
    cover: "https://c4.wallpaperflare.com/wallpaper/877/343/775/actresses-aishwarya-rai-wallpaper-preview.jpg",
  }
]

module.exports = Home1Data;