const tpost = [
    {
      id: 101,
      authorName: 'naruto uzumaki',
      date: "01. sept 2022",
      title: "US Promises to give Intel aid to locate the soldiers",
      cover: "https://c4.wallpaperflare.com/wallpaper/920/293/266/tower-block-new-york-usa-united-states-wallpaper-preview.jpg",
    },
    {
      id: 102,
      authorName: 'sasuke uchia',
      date: "30. aug 2022",
      title: "Renewable energy dead as industry waits for Policy",
      cover: "https://c4.wallpaperflare.com/wallpaper/646/835/697/full-size-for-desktop-nature-pictures-1920x1080-wallpaper-preview.jpg",
    },
    {
      id: 103,
      authorName: 'kakashi hatake',
      date: "25. aug 2022",
      title: "Mount Etna erupts fashion in nice looking pictures",
      cover: "https://c4.wallpaperflare.com/wallpaper/428/12/969/volcano-smoke-sky-snow-wallpaper-preview.jpg",
    },
    {
      id: 104,
      authorName: 'neji hyuga',
      date: "19. aug 2022",
      title: "Travelers spotted a bald eagle at the airport — but this isn't his first TSA line",
      cover: "https://c4.wallpaperflare.com/wallpaper/751/418/477/landscape-photography-of-green-grass-hills-during-daytime-rocky-mountain-national-park-rocky-mountain-national-park-wallpaper-preview.jpg",
    },
    {
      id: 105,
      authorName: 'madara uchia',
      date: "11. aug 2022",
      title: "Sharks mistaking feet for fish are likely behind Long Island attacks",
      cover: "https://c4.wallpaperflare.com/wallpaper/934/523/722/animals-shark-underwater-great-white-shark-wallpaper-preview.jpg",
    },
    {
      id: 106,
      authorName: 'might guy',
      date: "02. aug 2022",
      title: "What a pest! Spotted lanternflies are spreading in the U.S.",
      cover: "https://media.npr.org/assets/img/2022/08/17/ap21254030413843_wide-273914e5d32d03097106cda756190b7d93b01099-s700-c85.webp",
    },
    {
      id: 107,
      authorName: 'naruto uzumaki',
      date: "01. sept 2022",
      title: "US Promises to give Intel aid to locate the soldiers",
      cover: "https://c4.wallpaperflare.com/wallpaper/920/293/266/tower-block-new-york-usa-united-states-wallpaper-preview.jpg",
    },
    {
      id: 108,
      authorName: 'sasuke uchia',
      date: "30. aug 2022",
      title: "Renewable energy dead as industry waits for Policy",
      cover: "https://c4.wallpaperflare.com/wallpaper/646/835/697/full-size-for-desktop-nature-pictures-1920x1080-wallpaper-preview.jpg",
    },
    {
      id: 109,
      authorName: 'kakashi hatake',
      date: "25. aug 2022",
      title: "Mount Etna erupts fashion in nice looking pictures",
      cover: "https://c4.wallpaperflare.com/wallpaper/428/12/969/volcano-smoke-sky-snow-wallpaper-preview.jpg",
    },
    {
      id: 110,
      authorName: 'neji hyuga',
      date: "19. aug 2022",
      title: "Travelers spotted a bald eagle at the airport — but this isn't his first TSA line",
      cover: "https://c4.wallpaperflare.com/wallpaper/751/418/477/landscape-photography-of-green-grass-hills-during-daytime-rocky-mountain-national-park-rocky-mountain-national-park-wallpaper-preview.jpg",
    },
    {
      id: 111,
      authorName: 'madara uchia',
      date: "11. aug 2022",
      title: "Sharks mistaking feet for fish are likely behind Long Island attacks",
      cover: "https://c4.wallpaperflare.com/wallpaper/934/523/722/animals-shark-underwater-great-white-shark-wallpaper-preview.jpg",
    },
    {
      id: 112,
      authorName: 'might guy',
      date: "02. aug 2022",
      title: "What a pest! Spotted lanternflies are spreading in the U.S.",
      cover: "https://media.npr.org/assets/img/2022/08/17/ap21254030413843_wide-273914e5d32d03097106cda756190b7d93b01099-s700-c85.webp",
    },
  ]

  module.exports = tpost;